### ISSUE TITLE
Collections Transcoder

### ISSUE THREAD

**Issue by hvanness** [ACMILabs/transcoder#13]
Reinstate the collection team's old transcoder on the intel NUC.

Use Balena.
Deploy the master commit before Harry's xos updates.

**Comment by hvanness** [comment]
@dsamores 
Can you make a kb knowledge page saying:
The collections transcoder is running on the Skull NUC device, on the collections_transcoder_x86 balena application. It is running commit 92439243e6484dfb85a2d542ea27d6a0af64fad5 from the Acmilabs/transcoder master branch.

**Comment by dsamores** [comment]
KB page: https://kb.acmi.net.au/display/DD/Collections+transcoder
PDF: [DD-Collectionstranscoder-130220-1415-18.pdf](https://github.com/ACMILabs/transcoder/files/4196329/DD-Collectionstranscoder-130220-1415-18.pdf)
