### ISSUE TITLE
Update MacPro and VM transcoders

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/transcoder#25]
- [x] Update MacPro to latest Transcoder release
- [x] Update VM to latest Transcoder release
- [x] Debug smb issues after switch change

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to build & push transcoder updates to production](https://trello.com/c/6k8MvdHl/120-unable-to-build-push-transcoder-updates-to-production)
