### ISSUE TITLE
Add Github Action to run tests

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/transcoder#26]
- [ ] Add Github Actions to run Python tests
- [ ] Add Github Actions to run Javascript tests

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Github action to run tests](https://trello.com/c/hfLZ1oFU/124-add-github-action-to-run-tests)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to build & push transcoder updates to production](https://trello.com/c/6k8MvdHl/120-unable-to-build-push-transcoder-updates-to-production)
