### ISSUE TITLE
Transcode on the GPU

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/transcoder#27]
- [ ] Benchmark CPU vs GPU transcoding on our hardware
- [ ] If using Intel integrated GPU, try [QuickSync](https://superuser.com/questions/1428442/using-ffmpeg-to-encode-a-video-to-h264-using-intel-quicksync)

Thanks @shenki :-)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transcode on the GPU](https://trello.com/c/lhuIREa8/122-transcode-on-the-gpu)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to build & push transcoder updates to production](https://trello.com/c/6k8MvdHl/120-unable-to-build-push-transcoder-updates-to-production)
