### ISSUE TITLE
Unable to build Transcoder in production

### ISSUE THREAD

**Issue by ghost** [ACMILabs/transcoder#28]
**Issue**
Error returned when attempting to push Transcoder code onto a Balena Application.

i.e. the command 'balena push s__transcoder-x86' was run, however produced the following error...
`ERROR: Could not build wheels for yarl, multidict which use PEP 517 and cannot be installed directly`

Installing g++ seems to fix it, however causes an out of date chardet error, see https://github.com/aio-libs/aiohttp/issues/5366

**Comment by framigni** [comment]
@sam-maher-acmi can we close this ticket now ?

**Comment by ghost** [comment]
@framigni I believe can close this card.

The issue was not fixed, and will occur again the next time we go to change the Transcoder project. However the fix is trivial and will be captured in the next PR for the transcoder.

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to build & push transcoder updates to production](https://trello.com/c/6k8MvdHl/120-unable-to-build-push-transcoder-updates-to-production)
