### ISSUE TITLE
Spike: how do we modify the transcoder so we can use separate processes for Collection and Exhibition videos?

### ISSUE THREAD

**Issue by cogat** [ACMILabs/transcoder#5]
Currently the transcoder is geared towards collection videos only. We want a separate pipeline for Exhibition videos, and flexible pipelines in general.

I think we should define pipelines as sets of functions:

- file-generator - a function that generates file paths for input files to process
- processes - an ordered dictionary of lists of functions, each taking as input the output of the function before it.
- finally - final tasks to do with the output of all the processes once they have all completed.

**Comment by hvanness** [comment]
Greg can you close this since it sounds like you had a conversation with the conservators and this is no longer necessary.

**Comment by cogat** [comment]
Reopening as it is still unresolved @hvanness  

For both collection and exhibition videos we want to ensure there is an access copy and web copy uploaded to S3.

For collection videos, we transcode the master to make the access copy. But for exhibition videos, we usually want to upload the original, so long as it is below a given bitrate, say 20Mbps.

To close this ticket, let's look at some collection pres masters and see what bitrates we get. If they are consistently above 20Mbps, let's set that as the ceiling. If the master is below that ceiling, we upload it directly. If it is above 20Mbps, we transcode.

However, if collection pres masters are often 20Mbps or less, then we may need a different approach, perhaps an alternative transcoder with alternative settings and watch folders.
