### ISSUE TITLE
Modify the transcoder to make alternative outputs and communicate with XOS

### ISSUE THREAD

**Issue by cogat** [ACMILabs/transcoder#7]
For new exhibition files, define a process that:

- [ ] generates a hero image 33% of the way in to the video
- [x] uploads the output to S3
- [x] makes an API call to XOS that contains pertinent information about the video and thumbnail location, noting that there is not yet a URL for the video.

And another (parallel?) process that:
- [x] uploads the original video to S3
- [x] makes a PUT/PATCH request to XOS to update the video source URL with the result.

And another (parallel?) process that:
- [x] makes a web-friendly version of the video
- [x] makes a PUT/PATCH request to XOS to update the web-friendly video URL with the result.

**Comment by hvanness** [comment]
"generates a hero image 33% of the way in to the video" has a seperate ticket (#1329)

**Comment by hvanness** [comment]
Had a conversation with the team about how the transcoder codebase could be optimised (hashing less) and made more clear (review abstractions and file separation decisions). The team deemed it not a priority, or part of this ticket.

**Comment by cogat** [comment]
Where can this be reviewed?
