### ISSUE TITLE
Put the transcoder on the VR NUC

### ISSUE THREAD

**Issue by cogat** [ACMILabs/transcoder#9]
The VR NUC should be good at transcoding; certainly better than the Raspberry Pi.

This should be seen as a stop-gap solution until we can provision a VM to run the transcoder.

- [x] Find some RAM and HDD to put into the VR NUC. Raid a spare NUC if one can be found, otherwise ask ICT for spares, otherwise buy some.
- [x] Install and configure the transcoder on the VR NUC (it's a Balena app).
- [x] Ensure the transcoder is on the corp network.
- [x] Change the watch folder to smb://fsqnas2/RenewalVideo/Final
- [x] Decommission the previous transcoder/s (or leave them running if we can transcode in parallel)

**Comment by sighmon** [comment]
The RAM & SSD is in the post. Tracking: https://auspost.com.au/mypost/track/#/details/RB30034974
